### ISSUE TITLE
Cannot find preset's package after upgrade to v1.5

### ISSUE THREAD

**Issue by vladh91** [whitesource/renovate-on-prem#158]
We were using Renovate v1.3.1. After upgrading it to v1.5 we have started to see errors like 
```
INFO: Repository has invalid config (repository=pixel/panel-components)
       "error": {
         "validationError": "Cannot find preset's package (workfront:default)",
         "message": "config-validation",
         "stack": "Error: config-validation\n    at Object.resolveConfigPresets (/usr/src/app/node_modules/renovate/dist/config/presets/index.js:265:35)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Object.mergeRenovateConfig (/usr/src/app/node_modules/renovate/dist/workers/repository/init/merge.js:210:50)\n    at async Object.getRepoConfig (/usr/src/app/node_modules/renovate/dist/workers/repository/init/config.js:12:14)\n    at async Object.initRepo (/usr/src/app/node_modules/renovate/dist/workers/repository/init/index.js:26:14)\n    at async Object.renovateRepository (/usr/src/app/node_modules/renovate/dist/workers/repository/index.js:64:18)\n    at async e (/usr/src/app/src/server.js:1:40055)\n    at async startWorker (/usr/src/app/src/server.js:1:39258)"
       }
 INFO: Repository finished (repository=pixel/panel-components)
```
We are using custom presets for renovate.
Here are the relevant configurations:
1. renovate config itself
```
 platform: "gitlab",
      prCommitsPerRunLimit: 5,
      prFooter: "This MR has been generated by [Renovate Bot](https://renovatebot.com).\nPlease [log an issue](https://gitlab.workfront.tech/core-platform/devtools/renovate-helm/issues) if you encounter any.",
      // Default Onboarding Config
      onboardingConfig: {
        "extends": [
          "workfront:default",
          "workfront:phoenix",
          "workfront:devDependencies",
          "workfront:dashboard"
        ]
      },
      // Preserve repos between runs.
      // Reduces load by running `git fetch` instead of `git clone`
      persistRepoData: true,
      // Set this to "enabled" to have Renovate maintain a JSON file cache per-repository to speed up extractions.
      // WARN: This is experimental and could be removed.
      repositoryCache: "enabled",
    }
```

2. custom presets :
```
{
  "name": "renovate-config-workfront",
  "version": "1.11.0",
  "description": "Opinionated full preset configs for Renovate",
  "author": "Devtools <devtoolingandsupport@workfront.com",
  "contributors": [
    "Gabe Meola <gabrielmeola@workfront.com>"
  ],
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://gitlab.workfront.tech/core-platform/devtools/renovate"
  },
  "bugs": {
    "url": "https://gitlab.workfront.tech/core-platform/devtools/renovate/issues"
  },
  "scripts": {
    "prepack": "./updateReadme.js && git add README.md"
  },
  "renovate-config": {
    "default": {
      "description": "Workfront default configuration for all languages",
      "extends": [
        "config:base"
      ],
      "prHourlyLimit": 2,
      "assigneesFromCodeOwners": true,
      "prConcurrentLimit": 6,
      "postUpdateOptions": [
        "gomodTidy"
      ],
      "labels": [
        "dependencies"
      ]
    },
    ...
```
This is a relevant part of the configuration file in package.json and we are releasing it to our registry. From the logs of renovate it seems like its not able to find `workfront:default` preset which is described in the provided section.

**Comment by viceice** [comment]
I think it's because ROP v1.5 is now using renovate oss v25, wich no longer supports loading presets from custom npm registries.

You should switch to local preset hosting

https://docs.renovatebot.com/config-presets/#local-presets

**Comment by rarkins** [comment]
Related to @viceice’s comment, if you are mapping any .npmrc file into the container then it would definitely confirm it. Reference: https://github.com/whitesource/renovate-on-prem/releases/tag/1.4.0

**Comment by vladh91** [comment]
Yes, I am mapping .npmrc for my own private registry. The question is why Renovate doesn't support any more private npm registries? Is it done intentionally? It was really nice to store all the configs into one package and use it in other projects.

**Comment by rarkins** [comment]
We will be deprecating npm presets completely in future and recommend you use repository-based presets instead. Renovate is now a multi-language tool and repositories provide a simpler and non-language specific way to host private presets
